add Youtube and Gmail for account deletion data
j4n-e4t/deletr pull request #1
Opened 2024-10-24 19:59 UTC by Zyd8

-- can't see the newly icon being reflected on local dev frontend since it refers to what is in the online github repository.

2024-10-24 20:01 UTC, Zyd8 commented
Hello there, Julian. Hope, you're having a nice day. Do let me know if you have any issues with the changes I've done.

2024-10-24 21:25 UTC, j4n-e4t requested changes
Hi @Zyd8, thank you so much for contributing! I honestly thought no one would actually care about projects like this one but it's amazing to be proven wrong. This PR really made my day. Thank you! 🎉

I would change the spelling of YouTube to camel case since it's the official style. Other than that, awesome PR. 👍

2024-10-24 21:25 UTC, j4n-e4t commented on data/services.json
> +    "name": "Youtube",
```suggestion
    "name": "YouTube",
```

2024-10-24 21:26 UTC, merged

2024-10-24 21:27 UTC, j4n-e4t commented
> -- can't see the newly icon being reflected on local dev frontend since it refers to what is in the online github repository.

Also, I'm searching for a better way of hosting the images. GitHub isn't ideal for that exact reason. 😉

2024-10-25 03:43 UTC, Zyd8 commented
> Hi @Zyd8, thank you so much for contributing! I honestly thought no one would actually care about projects like this one but it's amazing to be proven wrong. This PR really made my day. Thank you! 🎉
> 
> I would change the spelling of YouTube to camel case since it's the official style. Other than that, awesome PR. 👍

@j4n-e4t Thank you also for making me contribute! I just love your project since I have _too much_ digital footprint in the internet. Stay tuned for more PRs!